[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycby4gptP5gGS-yGY_R_Js5SN4D5bGsvRtQm3t8g2X1yyoLaA93UC-4gMm7UQpwOpoH6hXA/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://t.me https://web.telegram.org;"
    X-Frame-Options = "ALLOW-FROM https://t.me"
